import { PolicyData } from './Types';
  export const sampleData: PolicyData[] = [
    {
      renewalPolicySummary: {
        pdn: '123456789',
        policyNumber: 'POL-1234',
        policyId: '567890',
        userId: 'user123',
        dealerContactInfo: {
          fullName: 'John Doe',
          positionTitle: 'Sales Manager',
          phoneNumber: '123-456-7890',
          faxNumber: '987-654-3210',
          emailId: 'johndoe@example.com',
        },
      },
      locations: [
        {
          locationInfo: {
            locationId: 'L123',
            dealershipName: 'Chat GPT Dealership',
            addressLine1: '123 Main St',
            addressLine2: '',
            city: 'Cityville',
            state: 'Stateville',
            zip: '12345',
            facilityUpdates: {
              lockBoxes: 'Yes',
              lockBoxesDesc: 'Secure lock boxes installed',
              securityOrSurveillance: 'Yes',
              securityOrSurveillanceDesc: '24/7 surveillance cameras',
              mailingOrBillingInfo: 'No',
              mailingOrBillingInfoDesc: '',
              floorPlanSource: 'ABC Bank',
              floorPlanSourceDesc: 'Floor plan financing with ABC Bank',
              lossPrevention: 'Yes',
              lossPreventionDesc: 'Loss prevention measures in place',
              otherInformation: 'none',
            },
          },
          premiumVehicles: {
            over200K: 'No',
            vin: '1234567899',
            year: '2022',
            make: 'Toyota',
            model: 'Camry',
            wholesaleValue: '25000',
            ownedByDealership: 'Yes',
            storedAtDealership: 'Yes',
            howVehicleStored: 'Indoor storage',
            primaryUseOfVehicle: 'Test drives',
          },
          manufacturersAllocation: [{ name: 'Toyota', allocationPercentage: '80' }],
          inventory: {
            q1Description: 'Jan. - March 2023',
            q1NewInventory: '50',
            q1UsedInventory: '25',
            q2Description: 'April - June 2023',
            q2NewInventory: '40',
            q2UsedInventory: '50',
            q3Description: 'July - Sept. 2023',
            q3NewInventory: '75',
            q3UsedInventory: '40',
            q4Description: 'Oct. - Dec. 2023',
            q4NewInventory: '60',
            q4UsedInventory: '75',
            annualDescription: 'Total inventory',
            demoVehicles: '5',
            shopRentals: '3',
            companyOwnedVehicles: '8',
          },
          documents: [{ uuid: '1234567899', fileName: 'document1.pdf' }],
        },
        {
          locationInfo: {
            locationId: 'L124',
            dealershipName: 'Dealer 2',
            addressLine1: '456 Elm St',
            addressLine2: '',
            city: 'Townsville',
            state: 'Stateland',
            zip: '67890',
            facilityUpdates: {
              lockBoxes: 'No',
              lockBoxesDesc: '',
              securityOrSurveillance: 'Yes',
              securityOrSurveillanceDesc: '24/7 surveillance cameras',
              mailingOrBillingInfo: 'Yes',
              mailingOrBillingInfoDesc: 'Billing information updated',
              floorPlanSource: 'XYZ Bank',
              floorPlanSourceDesc: 'Floor plan financing with XYZ Bank',
              lossPrevention: 'No',
              lossPreventionDesc: '',
              otherInformation: 'none',
            },
          },
          premiumVehicles: {
            over200K: 'Yes',
            vin: '9876543210',
            year: '2023',
            make: 'Honda',
            model: 'Accord',
            wholesaleValue: '30000',
            ownedByDealership: 'No',
            storedAtDealership: 'No',
            howVehicleStored: 'Outdoor storage',
            primaryUseOfVehicle: 'Rental',
          },
          manufacturersAllocation: [{ name: 'Honda', allocationPercentage: '60' }],
          inventory: {
            q1Description: 'Jan. - March 2023',
            q1NewInventory: '30',
            q1UsedInventory: '15',
            q2Description: 'April - June 2023',
            q2NewInventory: '35',
            q2UsedInventory: '20',
            q3Description: 'July - Sept. 2023',
            q3NewInventory: '50',
            q3UsedInventory: '30',
            q4Description: 'Oct. - Dec. 2023',
            q4NewInventory: '55',
            q4UsedInventory: '40',
            annualDescription: 'Total inventory',
            demoVehicles: '3',
            shopRentals: '5',
            companyOwnedVehicles: '10',
          },
          documents: [{ uuid: '9876543210', fileName: 'document2.pdf' }],
        },
        {
          locationInfo: {
            locationId: 'L125',
            dealershipName: 'Dealer 3',
            addressLine1: '789 Oak St',
            addressLine2: '',
            city: 'Villageville',
            state: 'Regionland',
            zip: '54321',
            facilityUpdates: {
              lockBoxes: 'Yes',
              lockBoxesDesc: 'Multiple secure lock boxes available',
              securityOrSurveillance: 'No',
              securityOrSurveillanceDesc: '',
              mailingOrBillingInfo: 'Yes',
              mailingOrBillingInfoDesc: 'Up-to-date billing information',
              floorPlanSource: 'LMN Bank',
              floorPlanSourceDesc: 'Floor plan financing with LMN Bank',
              lossPrevention: 'Yes',
              lossPreventionDesc: 'Comprehensive loss prevention measures',
              otherInformation: 'None',
            },
          },
          premiumVehicles: {
            over200K: 'No',
            vin: '1112233445',
            year: '2021',
            make: 'Ford',
            model: 'Mustang',
            wholesaleValue: '28000',
            ownedByDealership: 'Yes',
            storedAtDealership: 'Yes',
            howVehicleStored: 'Outdoor storage',
            primaryUseOfVehicle: 'Demo drives',
          },
          manufacturersAllocation: [{ name: 'Ford', allocationPercentage: '75' }],
          inventory: {
            q1Description: 'Jan. - March 2023',
            q1NewInventory: '40',
            q1UsedInventory: '20',
            q2Description: 'April - June 2023',
            q2NewInventory: '45',
            q2UsedInventory: '25',
            q3Description: 'July - Sept. 2023',
            q3NewInventory: '60',
            q3UsedInventory: '35',
            q4Description: 'Oct. - Dec. 2023',
            q4NewInventory: '50',
            q4UsedInventory: '40',
            annualDescription: 'Total inventory',
            demoVehicles: '4',
            shopRentals: '2',
            companyOwnedVehicles: '6',
          },
          documents: [{ uuid: '1112233445', fileName: 'document3.pdf' }],
        },
      ],
    },
    {
        renewalPolicySummary: {
        pdn: '123456789',
        policyNumber: 'POL-1234',
        policyId: '567890',
        userId: 'user123',
        dealerContactInfo: {
          fullName: 'John Doe',
          positionTitle: 'Sales Manager',
          phoneNumber: '123-456-7890',
          faxNumber: '987-654-3210',
          emailId: 'johndoe@example.com',
        },
      },
      locations: [
        {
          locationInfo: {
            locationId: 'L123',
            dealershipName: 'Chat GPT Dealership',
            addressLine1: '123 Main St',
            addressLine2: '',
            city: 'Cityville',
            state: 'Stateville',
            zip: '12345',
            facilityUpdates: {
              lockBoxes: 'Yes',
              lockBoxesDesc: 'Secure lock boxes installed',
              securityOrSurveillance: 'Yes',
              securityOrSurveillanceDesc: '24/7 surveillance cameras',
              mailingOrBillingInfo: 'No',
              mailingOrBillingInfoDesc: '',
              floorPlanSource: 'ABC Bank',
              floorPlanSourceDesc: 'Floor plan financing with ABC Bank',
              lossPrevention: 'Yes',
              lossPreventionDesc: 'Loss prevention measures in place',
              otherInformation: 'none',
            },
          },
          premiumVehicles: {
            over200K: 'No',
            vin: '1234567899',
            year: '2022',
            make: 'Toyota',
            model: 'Camry',
            wholesaleValue: '25000',
            ownedByDealership: 'Yes',
            storedAtDealership: 'Yes',
            howVehicleStored: 'Indoor storage',
            primaryUseOfVehicle: 'Test drives',
          },
          manufacturersAllocation: [{ name: 'Toyota', allocationPercentage: '80' }],
          inventory: {
            q1Description: 'Jan. - March 2023',
            q1NewInventory: '50',
            q1UsedInventory: '25',
            q2Description: 'April - June 2023',
            q2NewInventory: '40',
            q2UsedInventory: '50',
            q3Description: 'July - Sept. 2023',
            q3NewInventory: '75',
            q3UsedInventory: '40',
            q4Description: 'Oct. - Dec. 2023',
            q4NewInventory: '60',
            q4UsedInventory: '75',
            annualDescription: 'Total inventory',
            demoVehicles: '5',
            shopRentals: '3',
            companyOwnedVehicles: '8',
          },
          documents: [{ uuid: '1234567899', fileName: 'document1.pdf' }],
        },
        {
          locationInfo: {
            locationId: 'L124',
            dealershipName: 'Dealer 2',
            addressLine1: '456 Elm St',
            addressLine2: '',
            city: 'Townsville',
            state: 'Stateland',
            zip: '67890',
            facilityUpdates: {
              lockBoxes: 'No',
              lockBoxesDesc: '',
              securityOrSurveillance: 'Yes',
              securityOrSurveillanceDesc: '24/7 surveillance cameras',
              mailingOrBillingInfo: 'Yes',
              mailingOrBillingInfoDesc: 'Billing information updated',
              floorPlanSource: 'XYZ Bank',
              floorPlanSourceDesc: 'Floor plan financing with XYZ Bank',
              lossPrevention: 'No',
              lossPreventionDesc: '',
              otherInformation: 'none',
            },
          },
          premiumVehicles: {
            over200K: 'Yes',
            vin: '9876543210',
            year: '2023',
            make: 'Honda',
            model: 'Accord',
            wholesaleValue: '30000',
            ownedByDealership: 'No',
            storedAtDealership: 'No',
            howVehicleStored: 'Outdoor storage',
            primaryUseOfVehicle: 'Rental',
          },
          manufacturersAllocation: [{ name: 'Honda', allocationPercentage: '60' }],
          inventory: {
            q1Description: 'Jan. - March 2023',
            q1NewInventory: '30',
            q1UsedInventory: '15',
            q2Description: 'April - June 2023',
            q2NewInventory: '35',
            q2UsedInventory: '20',
            q3Description: 'July - Sept. 2023',
            q3NewInventory: '50',
            q3UsedInventory: '30',
            q4Description: 'Oct. - Dec. 2023',
            q4NewInventory: '55',
            q4UsedInventory: '40',
            annualDescription: 'Total inventory',
            demoVehicles: '3',
            shopRentals: '5',
            companyOwnedVehicles: '10',
          },
          documents: [{ uuid: '9876543210', fileName: 'document2.pdf' }],
        },
        {
          locationInfo: {
            locationId: 'L125',
            dealershipName: 'Dealer 3',
            addressLine1: '789 Oak St',
            addressLine2: '',
            city: 'Villageville',
            state: 'Regionland',
            zip: '54321',
            facilityUpdates: {
              lockBoxes: 'Yes',
              lockBoxesDesc: 'Multiple secure lock boxes available',
              securityOrSurveillance: 'No',
              securityOrSurveillanceDesc: '',
              mailingOrBillingInfo: 'Yes',
              mailingOrBillingInfoDesc: 'Up-to-date billing information',
              floorPlanSource: 'LMN Bank',
              floorPlanSourceDesc: 'Floor plan financing with LMN Bank',
              lossPrevention: 'Yes',
              lossPreventionDesc: 'Comprehensive loss prevention measures',
              otherInformation: 'None',
            },
          },
          premiumVehicles: {
            over200K: 'No',
            vin: '1112233445',
            year: '2021',
            make: 'Ford',
            model: 'Mustang',
            wholesaleValue: '28000',
            ownedByDealership: 'Yes',
            storedAtDealership: 'Yes',
            howVehicleStored: 'Outdoor storage',
            primaryUseOfVehicle: 'Demo drives',
          },
          manufacturersAllocation: [{ name: 'Ford', allocationPercentage: '75' }],
          inventory: {
            q1Description: 'Jan. - March 2023',
            q1NewInventory: '40',
            q1UsedInventory: '20',
            q2Description: 'April - June 2023',
            q2NewInventory: '45',
            q2UsedInventory: '25',
            q3Description: 'July - Sept. 2023',
            q3NewInventory: '60',
            q3UsedInventory: '35',
            q4Description: 'Oct. - Dec. 2023',
            q4NewInventory: '50',
            q4UsedInventory: '40',
            annualDescription: 'Total inventory',
            demoVehicles: '4',
            shopRentals: '2',
            companyOwnedVehicles: '6',
          },
          documents: [{ uuid: '1112233445', fileName: 'document3.pdf' }],
        },
      ],
    },
    
  ];
  
